import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ClientProvider from "@/redux/provider";
import { ToastContainer } from "react-toastify";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Service Clear",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <ClientProvider>
            {children}
            <ToastContainer />
        </ClientProvider>
      </body>
    </html>
  );
}
