import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import ClientProvider from "@/redux/provider";
import { ToastContainer } from "react-toastify";
import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from "@vercel/speed-insights/next"


const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Service Clear",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <ClientProvider>
            {children}
            <ToastContainer />
            <Analytics/>
            <SpeedInsights/>
        </ClientProvider>
      </body>
    </html>
  );
}
