import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ClientProvider from "@/redux/provider";
import { ToastContainer } from "react-toastify";


export const metadata: Metadata = {
    title: "Service Clear",
    description: "Generated by create next app",
};

export default function DefaultLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Navbar />
            {children}
            <Footer />
        </>
    );
}
